
admin-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9082

ribbon:
  eureka:
    enabled: false
  listOfServers: localhost:9082


logging:
  level:
    org.ckr.msdemo.adminservice.client: DEBUG