server:
  port: 9082
  context-path: /admin_service

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.58/adminservice?serverTimezone=UTC
  ldap:
    embedded:
      ldif: classpath:server.ldif
      base-dn: dc=springframework,dc=org
      port: 8389
ressrv:
  publickey: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEPS0uGZGdksBcNzRuLq2/6RD7gQOzZi0WhcVKCF/8ePlXg991xlOHEy7IP9ZWA+svWCVM22cts7v6hOaDoSFp7A==
  publicKeyUrl:
  publicKeyAlgorithm: EC
  verifyAlgorithm: SHA256withECDSA

logging:
  level:
    org.springframework:
      web: DEBUG
      orm: DEBUG
      security: DEBUG
    org.ckr: DEBUG

endpoints:
  enabled: true
  sensitive: false

management:
  context-path: /manage
  port: 9081
  address: 127.0.0.1
  security:
    enabled: false

jolokia.config.debug: true